server:
  port: 8100
eureka:
  instance:
    ###注册到eurekaip地址
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8100/eureka/
      ###因为自己是为注册中心，不需要自己注册自己
    register-with-eureka: false
        ###因为自己是为注册中心，不需要检索服务
    fetch-registry: false
  server:
    # 测试时关闭自我保护机制，保证不可用服务及时踢出
    enable-self-preservation: true

    ##剔除失效服务间隔
    eviction-interval-timer-in-ms: 2000

spring:
    application:
      name: app-itmayiedu-eureka

